import os
import base64

os.makedirs('static/icons', exist_ok=True)

icon_192 = base64.b64decode(
    'iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAC'
    'L0lEQVR4nO3SMQ0AMAzAsPLn36UbIMCKu+SWABbz6wPgJgOwmgFYzQCsZgBWMwCrGYDVDMBqBmA1'
    'A7CaAVjNAKxmAFYzAKsZgNUMwGoGYDUDsJoBWM0ArGYAVjMAqxmA1QzAagZgNQOwmgFYzQCsZgBW'
    'MwCrGYDVDMBqBmA1A7CaAVjNAKxmAFYzAKsZgNUMwGoGYDUDsJoBWM0ArGYAVjMAqxmA1QzAagZg'
    'NQOwmgFYzQCsZgBWMwCrGYDVDMBqBmA1A7CaAVjNAKxmAFYzAKsZgNUMwGoGYDUDsJoBWM0ArGYA'
    'VjMAqxmA1QzAagZgNQOwmgFYzQCsZgBWMwCrGYDVDMBqBmA1A7CaAVjNAKxmAFYzAKsZgNUMwGoG'
    'YDUDsJoBWM0ArGYAVjMAqxmA1QzAagZgNQOwmgFYzQCsZgBWMwCrGYDVDMBqBmA1A7CaAVjNAKxm'
    'AFYzAKsZgNUMwGoGYDUDsJoBWM0ArGYAVjMAqxmA1QzAagZgNQOwmgFYzQCsZgBWMwCrGYDVDMBq'
    'BmA1A7CaAVjNAKxmAFYzAKsZgNUMwGoGYDUDsJoBWM0ArGYAVjMAqxmA1QzAagZgNQOwmgFYzQCs'
    'ZgBWMwCrGYDVDMBqBmA1A7CaAVjNAKxmAFYzAKsZgNUMwGoGYDUDsJoBWM0ArGYAVjMAqxmA1QzA'
    'agZgNQOwmgFYzQCsZgBWMwCrGYDVDMBqBmA1A7CaAVjNAKxmAFYzAKsZgNUMwGoGYDUDsJoBWM0A'
    'rGYAVjMAqxmA1QzAagZgNQOwmgFY7QMLrgTIqVP3ZAAAAABJRU5ErkJggg=='
)

icon_512 = base64.b64decode(
    'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAC'
    'U0lEQVR4nO3QQREAAAzCsIPi33MABQ+SFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOD/9QADdQABhAZmKAAAAABJ'
    'RU5ErkJggg=='
)

with open('static/icons/icon-192x192.png', 'wb') as f:
    f.write(icon_192)

with open('static/icons/icon-512x512.png', 'wb') as f:
    f.write(icon_512)

print("Icon files created successfully!")
